# -*- coding: utf-8 -*-
"""mycaptain_ai_project_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124MUo0UZLdpUEvIAsFbDWb14rMaPUn-n
"""

print("Hello world")
